Exception in thread Thread-40:
Traceback (most recent call last):
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    history = fit(epochs, net, train_ds, val_ds, device, opt = optimizer)
  File "/home/jeffreymo572/Kaggles/common/utils.py", line 123, in fit
    loss.backward()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt